project:
  type: website
  output-dir: docs

website:
  title: "Home"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Jangseunggyu
      - icon: instagram
        href: https://instagram.com
format:
  html:
    theme:
      - litera
      - brand
    css: styles.css



